version: "3.1"

networks:
  default:
    external:
      name: ampnet

secrets:
  certificate_appcelerator:
    external: true
  certificate_atomiq_fc:
    external: true

services:

  proxy:
    image: dockercloud/haproxy
    networks:
      - default
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints: [node.role == manager]
    environment:
      CERT_FOLDER: "/run/secrets"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.amp.role: "infrastructure"
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    secrets:
      - source: certificate_atomiq_fc
        target: cert0.pem
        mode: 0400
      - source: certificate_appcelerator
        target: cert1.pem
        mode: 0400
