global:
  scrape_interval:     15s
  external_labels:
    monitor: 'pinger-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'pinger'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:3000']
